// Generated by Wrangler by running `wrangler types`

interface Env {
	AUTH_ISSUER: string;
	AUTH_PROJECT_ID: string;
	DATABASE_URL: string;
	PYLON_SECRET: string;
	ORG_USER_MANAGER_TOKEN: string;
	AUTH_KEY: string;
	DB: D1Database;
}
